### ISSUE TITLE
Cannot disable styling for Hyprland (Option not exist)

### ISSUE THREAD

**Issue by Lem0nbleach** [danth/stylix#699]
```
error:
       … while calling the 'seq' builtin
         at /nix/store/8fwsiv0hd7nw1brkvka0jf1frk3m7qkr-source/lib/modules.nix:334:18:
          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       … while calling the 'throw' builtin
         at /nix/store/8fwsiv0hd7nw1brkvka0jf1frk3m7qkr-source/lib/modules.nix:310:18:
          309|                     ''
          310|             else throw baseMsg
             |                  ^
          311|         else null;

       error: The option `stylix.targets.hyprpaper' does not exist. Definition values:
       - In `/nix/store/46zkgx3yx3l1yvc17lwqsc9ick8nk7kc-source/stylix.nix':
           {
             enable = false;
           }
```

This the error that I get when I try to disable Stylix's styling for Hyprland. 

Something worth to mention is the reason for me to disable the styling from Stylix: Hyprland no longer has <decoration:shadow:color> while Stylix still automatically includes that line which produces an error.

Should I make a new issue regarding that as well?

**Comment by trueNAHO** [comment]
> ```
> error:
>        … while calling the 'seq' builtin
>          at /nix/store/8fwsiv0hd7nw1brkvka0jf1frk3m7qkr-source/lib/modules.nix:334:18:
>           333|         options = checked options;
>           334|         config = checked (removeAttrs config [ "_module" ]);
>              |                  ^
>           335|         _module = checked (config._module);
>
>        … while calling the 'throw' builtin
>          at /nix/store/8fwsiv0hd7nw1brkvka0jf1frk3m7qkr-source/lib/modules.nix:310:18:
>           309|                     ''
>           310|             else throw baseMsg
>              |                  ^
>           311|         else null;
>
>        error: The option `stylix.targets.hyprpaper' does not exist. Definition values:
>        - In `/nix/store/46zkgx3yx3l1yvc17lwqsc9ick8nk7kc-source/stylix.nix':
>            {
>              enable = false;
>            }
> ```
>
> This the error that I get when I try to disable Stylix's styling for Hyprland.

This option should exist since commit https://github.com/danth/stylix/commit/f13c946181730f98e1a5cd09714100490207b250. What version are your inputs (Stylix and Nixpkgs) on?

> Something worth to mention is the reason for me to disable the styling from Stylix: Hyprland no longer has decoration:shadow:color while Stylix still automatically includes that line which produces an error.
>
> Should I make a new issue regarding that as well?

Is this not already resolved by commit https://github.com/danth/stylix/commit/5ab1207b2fdeb5a022f2dd7cccf6be760f1b150f and a duplicate of https://github.com/danth/stylix/issues/689?

**Comment by Lem0nbleach** [comment]
@trueNAHO I am incredibly sorry
I simply forgotten to reboot the system after a whole system update and thus hyprland's version was not changed.
The issue was indeed solved perfectly by https://github.com/danth/stylix/commit/5ab1207b2fdeb5a022f2dd7cccf6be760f1b150f

As for that option, I still do not have it. 

> This option should exist since commit f13c946. What version are your inputs (Stylix and Nixpkgs) on?
If I interpreted it correctly, Nixpkgs is on the current unstable channel and stylix is from flake, pulled straight from github.

**Comment by trueNAHO** [comment]
> @trueNAHO I am incredibly sorry I simply forgotten to reboot the system after a whole system update and thus hyprland's version was not changed. The issue was indeed solved perfectly by [5ab1207](https://github.com/danth/stylix/commit/5ab1207b2fdeb5a022f2dd7cccf6be760f1b150f)

Glad to hear you resolved it.

> As for that option, I still do not have it.
>
> > This option should exist since commit [f13c946](https://github.com/danth/stylix/commit/f13c946181730f98e1a5cd09714100490207b250). What version are your inputs (Stylix and Nixpkgs) on?
>
> If I interpreted it correctly [...] stylix is from flake, pulled straight from github.

Does your Stylix input have commit https://github.com/danth/stylix/commit/f13c946181730f98e1a5cd09714100490207b250? You could check this by comparing the commit time of this commit and the `lastModified` value of your Stylix input in `flake.lock`.

**Comment by Lem0nbleach** [comment]
> Does your Stylix input have commit f13c946? You could check this by comparing the commit time of this commit and the lastModified value of your Stylix input in flake.lock.

Yes I believe so, the number is 1735151068; that would be Dec 25 of this year is that right?

**Comment by trueNAHO** [comment]
> > Does your Stylix input have commit [f13c946](https://github.com/danth/stylix/commit/f13c946181730f98e1a5cd09714100490207b250)? You could check this by comparing the commit time of this commit and the lastModified value of your Stylix input in flake.lock.
>
> Yes I believe so, the number is 1735151068; that would be Dec 25 of this year is that right? That was yesterday

Correct:

```console
$ date --date @1735151068
Wed Dec 25 07:24:28 PM CET 2024
```

I am unable to replicate your issue. Can you try the https://github.com/danth/stylix/pull/701 PR?

**Comment by Lem0nbleach** [comment]
Apologies for duplication, and being a complete noob even at github, thought that maybe the pull request is not the right place to ask: What should the url path be? 

I couldn't figure out what the url should be in the input

**Comment by trueNAHO** [comment]
> are there other possible issues from my end instead of the repo being faulty?

Maybe your setup is the problem, although I cannot imagine why that would be the case. Can you share your configuration or a minimal reproducible example?

**Comment by Lem0nbleach** [comment]
@trueNAHO I am incredibly sorry I forgot to reply
I have my entire config in https://github.com/Lem0nbleach/nixos-config

**Comment by trueNAHO** [comment]
Is the following line the problem:

> ```nix
>   #stylix.targets.hyprpaper.enable = true;
> ```
>
> -- [Lem0nbleach, "nixos-config"](https://github.com/Lem0nbleach/nixos-config/blob/620d773b6a2163926cc9de04a69a6d74dee68c1b/stylix.nix#L31)

Maybe the problem stems from the fact that we only provide Home Manager modules for the Hyprland and Hyprpaper modules.

**Comment by Lem0nbleach** [comment]
> Is the following line the problem:

Yes that is exactly it. 

> Maybe the problem stems from the fact that we only provide Home Manager modules for the Hyprland and Hyprpaper modules.

Perfectly makes sense. I am afraid that I don't quite want to deal with switching to module home manager for now , a problem for the future me it is!
